### PR TITLE
Update gitleaks_github_actions.yml

### PR DESCRIPTION
**Pull request by sb-seanblackford**
Moving the whitelist file to an external repo so that changes don't require a PR within this project.

**JIRA Tickets:**

[AB2D-42](https://jira.cms.gov/browse/AB2D-42) - Description

***Related Tickets***

[AB2D-41](https://jira.cms.gov/browse/AB2D-41) - Reason it's related
 
### Security Implications

- [ ] This PR adds new software dependencies
- [ ] This PR modifies or invalidates our security controls
- [ ] This PR stores or transmits data that was not stored or transmitted before

- [ ] This PR requires additional review of its security implications for other reasons

### Submitter Checklist

- [ ] This PR includes any required documentation changes, (`README`, changelog / release notes, website).
- [ ] All tech debt and/or shortcomings introduced by this PR are detailed in `TODO` and/or `FIXME` comments.
- [ ] Code checked for PHI/PII exposure

### CODE REVIEW

**Review by lhanekam — COMMENTED** [review]
LGTM

**Review by nflearl — APPROVED** [review]
Initially I was concerned that this was a potential end-around having security configuration outside the scope of normal AB2D purview but after a conversation with Lonnie, we are both comfortable in the change.

Changes to this file affect AB2D build process only, not actual runtime.  So if something breaking was introduced, it won't affect consumers of our service, just our ability to build and deploy.

One open question is if there is value in having settings like this in a global project (applicable to all of SemanticBits security concerns) instead of duplicating into additional repos on a per-project basis.

**Comment by sb-seanblackford** [comment]
> 
> 
> Initially I was concerned that this was a potential end-around having security configuration outside the scope of normal AB2D purview but after a conversation with Lonnie, we are both comfortable in the change.
> 
> Changes to this file affect AB2D build process only, not actual runtime. So if something breaking was introduced, it won't affect consumers of our service, just our ability to build and deploy.
> 
> One open question is if there is value in having settings like this in a global project (applicable to all of SemanticBits security concerns) instead of duplicating into additional repos on a per-project basis.

Thanks! If this does become an issue in the future and we need more eyes on changes, we can certainly move this back to the repo to get more eyes on it.

While we do have a "baseline" for what is allowed in each repo, we've found that due to the differences in project coding standards, languages, and various other things that end up in the repo, it's cleaner to have a separate gitleaks file for each repo. Otherwise we might end up with some really large and unmaintainable toml files.

**Review by lhanekam — COMMENTED** [review]
LGTM

**Review by lhanekam — APPROVED** [review]

**Pull request merged**
